### ISSUE TITLE
About Automated Process

### ISSUE THREAD

**Issue by MrChenA** [alexMyG/AndroPyTool#5]
The analysis of Droidbox is currently not automated except for installing and starting packages. Can AndroPyTool test all functions of an App or a part of them? How can it implement that?

**Comment by alexMyG** [comment]
DroidBox uses MonkeyRunner to launch multiple random actions (i.e. turn the volume up or touch the screen) to the emulator, trying to trigger different responses by the app. Meanwhile, all events are captured and saved by DroidBox through logcat. I think you could modify the tool in order to launch more specific actions to interact with the app, but I am not sure how can you do that. Take a look at MonkeyRunner documentation.

**Comment by MrChenA** [comment]
Ok,thanks!
